# Stage 1: Build the React app
FROM node:20 AS build

# WORKDIR /app
# COPY client/package.json client/package-lock.json ./
# RUN npm install
# COPY client ./
# RUN npm run build

# CMD ["node", "server.js"]
